# Generated by Django 2.2 on 2019-04-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_index', models.CharField(max_length=12)),
                ('profession_rus', models.CharField(max_length=12)),
                ('items_string', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='SearchedBody',
        ),
    ]
